import { randomBytes } from "node:crypto";
import { sql } from "kysely";
import { z } from "zod";
import { db } from "../../config/db.js";
import { withPlatformContext } from "../../context/tenantContext.js";
import { hashPassword } from "../../security/password.js";
import { hashToken } from "../../security/sessionToken.js";
import { loadEmailConfig, sendOrganizationAdminInvitationEmail } from "../email/email.service.js";
export const createPlatformOrganizationSchema=z.object({name:z.string().trim().min(2).max(160),organizationType:z.enum(["HOME_CARE_AGENCY","RESIDENTIAL_CARE_HOME"]),status:z.enum(["trial","active"]).default("trial")});
export const inviteOrganizationAdminSchema=z.object({email:z.string().trim().email().max(254)});export const organizationAdminInvitationTokenSchema=z.object({token:z.string().regex(/^[a-f0-9]{64}$/i)});export const activateOrganizationAdminInvitationSchema=organizationAdminInvitationTokenSchema.extend({password:z.string().min(12).max(128)});export type CreatePlatformOrganizationInput=z.infer<typeof createPlatformOrganizationSchema>;
export interface InviteOrganizationAdminResult{invitation:{id:string;email:string;expires_at:string;organization_id:string;organization_name:string};rawToken:string;emailDelivery:{status:"sent"|"failed";messageId?:string;error?:string}}
export class OrganizationAdminInvitationError extends Error{constructor(public readonly code:string){super(code);this.name="OrganizationAdminInvitationError";}}
function translateInvitationError(error:unknown):never{const message=error instanceof Error?error.message:"";const known=["INVITATION_NOT_AVAILABLE","INVITATION_EXPIRED","ACCOUNT_ALREADY_EXISTS","INVITATION_IDENTITY_MISMATCH","ACCOUNT_DISABLED","INVALID_ACTIVATION","ROLE_NOT_CONFIGURED"];const code=known.find(c=>message.includes(c));if(code)throw new OrganizationAdminInvitationError(code);throw error;}
export async function listPlatformOrganizations(userId:string){return withPlatformContext(userId,async trx=>(await sql<{id:string;name:string;organization_type:string;status:string;created_at:Date}>`SELECT id,name,organization_type,status,created_at FROM organizations WHERE archived_at IS NULL ORDER BY created_at DESC`.execute(trx)).rows);}
export async function getPlatformOrganizationOverview(userId:string,organizationId:string){return withPlatformContext(userId,async trx=>{const org=(await sql<{id:string;name:string;organization_type:string;status:string}>`SELECT id,name,organization_type,status FROM organizations WHERE id=${organizationId} AND archived_at IS NULL LIMIT 1`.execute(trx)).rows[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");const workers=(await sql<{membership_id:string;worker_id:string;display_name:string|null;internal_role:string|null;status:string}>`SELECT owm.id membership_id,owm.worker_id,w.display_name,owm.internal_role,owm.status::text status FROM organization_worker_memberships owm JOIN workers w ON w.id=owm.worker_id WHERE owm.organization_id=${organizationId} ORDER BY w.display_name NULLS LAST,owm.created_at DESC`.execute(trx)).rows;const locations=(await sql<{id:string;name:string}>`SELECT id,name FROM locations WHERE organization_id=${organizationId} AND archived_at IS NULL ORDER BY name`.execute(trx)).rows;const residents=(await sql<{id:string;display_name:string}>`SELECT id,coalesce(preferred_name,trim(concat_ws(' ',first_name,last_name)),'Residente') display_name FROM care_recipients WHERE organization_id=${organizationId} AND archived_at IS NULL ORDER BY coalesce(preferred_name,first_name,last_name) NULLS LAST`.execute(trx)).rows;return{organization:org,workers,locations,residents};});}
export async function getPlatformOrganizationResident(userId:string,organizationId:string,residentId:string){return withPlatformContext(userId,async trx=>{const org=(await sql<{id:string}>`SELECT id FROM organizations WHERE id=${organizationId} AND archived_at IS NULL LIMIT 1`.execute(trx)).rows[0];if(!org)throw new Error("ORGANIZATION_NOT_FOUND");const resident=(await sql<{id:string;organization_id:string;first_name:string;last_name:string;preferred_name:string|null;date_of_birth:string|null;allergies:string[]|null;preferences:unknown;routines:unknown;status:string;room_id:string|null;location_name:string|null;room_name:string|null;created_at:string;updated_at:string}>`SELECT cr.id,cr.organization_id,cr.first_name,cr.last_name,cr.preferred_name,cr.date_of_birth,cr.allergies,cr.preferences,cr.routines,cr.status::text status,cr.room_id,l.name location_name,r.name room_name,cr.created_at,cr.updated_at FROM care_recipients cr LEFT JOIN rooms r ON r.id=cr.room_id AND r.organization_id=cr.organization_id LEFT JOIN locations l ON l.id=r.location_id AND l.organization_id=cr.organization_id WHERE cr.id=${residentId} AND cr.organization_id=${organizationId} AND cr.archived_at IS NULL LIMIT 1`.execute(trx)).rows[0];if(!resident)throw new Error("RESIDENT_NOT_FOUND");return resident;});}
export async function createPlatformOrganization(userId:string,input:CreatePlatformOrganizationInput){return withPlatformContext(userId,async trx=>{const created=await sql<{id:string;name:string;organization_type:string;status:string;created_at:Date}>`INSERT INTO organizations (name,organization_type,status) VALUES (${input.name},${input.organizationType}::organization_type_enum,${input.status}::organization_status_enum) RETURNING id,name,organization_type,status,created_at`.execute(trx);const organization=created.rows[0];await sql`INSERT INTO organization_settings (organization_id) VALUES (${organization.id})`.execute(trx);return organization;});}
export async function inviteOrganizationAdmin(userId:string,organizationId:string,emailInput:string):Promise<InviteOrganizationAdminResult>{return withPlatformContext(userId,async trx=>{const org=await sql<{id:string;name:string}>`SELECT id,name FROM organizations WHERE id=${organizationId} AND archived_at IS NULL LIMIT 1`.execute(trx);if(!org.rows[0])throw new Error("ORGANIZATION_NOT_FOUND");const email=emailInput.trim().toLowerCase();await sql`UPDATE access_invitations SET status=CASE WHEN expires_at<=now() THEN 'expired'::access_invitation_status_enum ELSE 'revoked'::access_invitation_status_enum END,revoked_at=CASE WHEN expires_at>now() THEN now() ELSE revoked_at END,updated_at=now() WHERE organization_id=${organizationId} AND invitation_type='organization_admin' AND lower(email)=${email} AND status='pending'`.execute(trx);const rawToken=randomBytes(32).toString("hex"),tokenHash=hashToken(rawToken),expiresAt=new Date(Date.now()+7*86400000).toISOString();const inserted=await sql<{id:string;email:string;expires_at:string}>`INSERT INTO access_invitations(organization_id,invited_by_user_id,invitation_type,email,token_hash,expires_at) VALUES(${organizationId},${userId},'organization_admin',${email},${tokenHash},${expiresAt}) RETURNING id,email,expires_at`.execute(trx);const inviterResult=await sql<{email:string|null}>`SELECT email FROM users WHERE id=${userId} LIMIT 1`.execute(trx);const invitation={...inserted.rows[0],organization_id:organizationId,organization_name:org.rows[0].name};const emailDelivery=await sendOrganizationAdminInvitationEmail({recipientEmail:email,organizationName:org.rows[0].name,activationToken:rawToken,invitedByEmail:inviterResult.rows[0]?.email||"admin@etnara.care"},loadEmailConfig());return{invitation,rawToken,emailDelivery};});}
export async function inspectOrganizationAdminInvitation(rawToken:string){try{const result=await sql<{invitation_type:string;email_masked:string;organization_name:string;target_name:string;account_exists:boolean;expires_at:string}>`SELECT * FROM app_inspect_access_invitation(${hashToken(rawToken)})`.execute(db);const invitation=result.rows[0];if(!invitation||invitation.invitation_type!=="organization_admin")throw new OrganizationAdminInvitationError("INVITATION_NOT_AVAILABLE");return invitation;}catch(error){if(error instanceof OrganizationAdminInvitationError)throw error;return translateInvitationError(error);}}
export async function activateOrganizationAdminInvitation(rawToken:string,password:string){const inspection=await inspectOrganizationAdminInvitation(rawToken);if(inspection.account_exists)throw new OrganizationAdminInvitationError("ACCOUNT_ALREADY_EXISTS");const passwordHash=await hashPassword(password);try{const result=await sql<{user_id:string;organization_id:string;invitation_type:string}>`SELECT * FROM app_activate_organization_admin_invitation(${hashToken(rawToken)},${passwordHash},NULL)`.execute(db);return result.rows[0];}catch(error){return translateInvitationError(error);}}