import { sql } from "kysely";
import { z } from "zod";
import { withTenantContext } from "../../context/tenantContext.js";

export class OperationsForbiddenError extends Error { constructor(){ super("OPERATIONS_FORBIDDEN"); } }
export const escalationSchema=z.object({alertKey:z.string().min(1).max(200),category:z.enum(["uncovered_shift","missed_check_in","expiring_credential","open_incident","pending_timesheet"]),relatedEntityType:z.string().min(1).max(50),relatedEntityId:z.string().uuid()});
async function manager(trx:unknown){const r=await sql<{ok:boolean}>`SELECT app_is_org_manager() ok`.execute(trx as never);if(!r.rows[0]?.ok)throw new OperationsForbiddenError()}
type Alert={key:string;category:string;severity:"critical"|"warning"|"info";title:string;detail:string;relatedEntityType:string;relatedEntityId:string;actionPath:string;occurredAt:string;escalatedAt:string|null};
export async function getOperationsCenter(userId:string,organizationId:string){return withTenantContext({userId,organizationId},async trx=>{await manager(trx);
 const shifts=await sql<any>`SELECT s.id,s.scheduled_start,s.scheduled_end,trim(concat_ws(' ',cr.first_name,cr.last_name)) recipient,
 EXISTS(SELECT 1 FROM assignments a WHERE a.shift_id=s.id AND a.organization_id=s.organization_id AND a.response_status='accepted') accepted,
 EXISTS(SELECT 1 FROM verification_events v WHERE v.shift_id=s.id AND v.event_type='check_in') checked_in
 FROM shifts s LEFT JOIN care_recipients cr ON cr.id=s.care_recipient_id WHERE s.organization_id=${organizationId} AND s.status<>'cancelled' AND s.scheduled_end>now() AND s.scheduled_start<now()+interval '7 days'`.execute(trx);
 const credentials=await sql<any>`SELECT c.id,c.expires_at,w.display_name FROM credentials c JOIN workers w ON w.id=c.worker_id JOIN organization_worker_memberships m ON m.worker_id=w.id WHERE m.organization_id=${organizationId} AND m.status='active' AND c.status='active' AND c.expires_at BETWEEN current_date AND current_date+30`.execute(trx);
 const incidents=await sql<any>`SELECT i.id,i.created_at,i.severity,trim(concat_ws(' ',cr.first_name,cr.last_name)) recipient FROM incidents i JOIN care_recipients cr ON cr.id=i.care_recipient_id WHERE i.organization_id=${organizationId} AND i.status<>'resolved'`.execute(trx);
 const sheets=await sql<any>`SELECT t.id,t.created_at,t.status,w.display_name FROM timesheets t JOIN organization_worker_memberships m ON m.id=t.organization_worker_membership_id JOIN workers w ON w.id=m.worker_id WHERE t.organization_id=${organizationId} AND t.status IN ('pending','disputed')`.execute(trx);
 const escalations=await sql<any>`SELECT alert_key,escalated_at FROM operational_alert_escalations WHERE organization_id=${organizationId}`.execute(trx);const esc=new Map(escalations.rows.map(x=>[x.alert_key,x.escalated_at]));const alerts:Alert[]=[];const now=Date.now();
 for(const s of shifts.rows){const start=new Date(s.scheduled_start).getTime();if(!s.accepted){const key=`uncovered_shift:${s.id}`;alerts.push({key,category:"uncovered_shift",severity:start-now<86400000?"critical":"warning",title:"Turno sin cubrir",detail:`${s.recipient||"Residente"} · ${new Date(s.scheduled_start).toLocaleString("es-PR")}`,relatedEntityType:"shift",relatedEntityId:s.id,actionPath:`/agency/shifts/${s.id}`,occurredAt:s.scheduled_start,escalatedAt:esc.get(key)||null})}else if(start<now-900000&&!s.checked_in&&new Date(s.scheduled_end).getTime()>now){const key=`missed_check_in:${s.id}`;alerts.push({key,category:"missed_check_in",severity:"critical",title:"Falta registrar entrada",detail:`${s.recipient||"Residente"} · turno iniciado`,relatedEntityType:"shift",relatedEntityId:s.id,actionPath:`/agency/shifts/${s.id}`,occurredAt:s.scheduled_start,escalatedAt:esc.get(key)||null})}}
 for(const c of credentials.rows){const key=`expiring_credential:${c.id}`;alerts.push({key,category:"expiring_credential",severity:"warning",title:"Credencial próxima a vencer",detail:`${c.display_name||"Cuidador"} · vence ${c.expires_at}`,relatedEntityType:"credential",relatedEntityId:c.id,actionPath:"/agency/compliance",occurredAt:c.expires_at,escalatedAt:esc.get(key)||null})}
 for(const i of incidents.rows){const key=`open_incident:${i.id}`;alerts.push({key,category:"open_incident",severity:String(i.severity).toLowerCase().includes("high")?"critical":"warning",title:"Incidente pendiente",detail:`${i.recipient} · ${i.severity}`,relatedEntityType:"incident",relatedEntityId:i.id,actionPath:`/agency/incidents/${i.id}`,occurredAt:i.created_at,escalatedAt:esc.get(key)||null})}
 for(const t of sheets.rows){const key=`pending_timesheet:${t.id}`;alerts.push({key,category:"pending_timesheet",severity:t.status==="disputed"?"warning":"info",title:t.status==="disputed"?"Horas en disputa":"Horas por revisar",detail:t.display_name||"Cuidador",relatedEntityType:"timesheet",relatedEntityId:t.id,actionPath:"/agency/timesheets",occurredAt:t.created_at,escalatedAt:esc.get(key)||null})}
 const counts={critical:alerts.filter(a=>a.severity==="critical").length,warning:alerts.filter(a=>a.severity==="warning").length,info:alerts.filter(a=>a.severity==="info").length};
 const rank:Record<Alert["severity"],number>={critical:0,warning:1,info:2};
 return{generatedAt:new Date().toISOString(),summary:{total:alerts.length,...counts},alerts:alerts.sort((a,b)=>rank[a.severity]-rank[b.severity])};
 })}
export async function escalateOperationalAlert(userId:string,organizationId:string,input:z.infer<typeof escalationSchema>){return withTenantContext({userId,organizationId},async trx=>{await manager(trx);const r=await sql<{id:string}>`SELECT app_escalate_operational_alert(${organizationId},${input.alertKey},${input.category},${input.relatedEntityType},${input.relatedEntityId}) id`.execute(trx);return{id:r.rows[0].id}})}
