import { randomUUID } from "node:crypto";
import { sql } from "kysely";
import { withTenantContext } from "../../context/tenantContext.js";
import { createPrivateDownloadUrl, uploadPrivateObject } from "../storage/objectStorage.js";
export class EstablishmentDocumentForbiddenError extends Error{constructor(){super("ESTABLISHMENT_DOCUMENT_FORBIDDEN");}}
export class EstablishmentDocumentNotFoundError extends Error{constructor(){super("ESTABLISHMENT_DOCUMENT_NOT_FOUND");}}
async function allowed(trx:any,o:string,e:string){const r=await sql<{allowed:boolean}>`SELECT EXISTS(SELECT 1 FROM locations l WHERE l.id=${e} AND l.organization_id=${o} AND (app_is_org_manager() OR app_is_superadmin() OR app_is_establishment_admin(${e}))) allowed`.execute(trx);if(!r.rows[0]?.allowed)throw new EstablishmentDocumentForbiddenError();}
export async function listEstablishmentDocuments(u:string,o:string,e:string){return withTenantContext({userId:u,organizationId:o},async trx=>{await allowed(trx,o,e);const r=await sql<any>`SELECT id,document_type,title,file_name,content_type,size_bytes,issued_on,expires_on,notes,created_at FROM establishment_documents WHERE organization_id=${o} AND establishment_id=${e} AND archived_at IS NULL ORDER BY created_at DESC`.execute(trx);return r.rows;});}
export async function uploadEstablishmentDocument(u:string,o:string,e:string,input:{documentType:string;title:string;fileName:string;contentType:string;issuedOn?:string;expiresOn?:string;notes?:string},body:Buffer){return withTenantContext({userId:u,organizationId:o},async trx=>{await allowed(trx,o,e);const id=randomUUID();const key=`establishment-documents/${o}/${e}/${id}/${input.fileName.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await uploadPrivateObject(key,input.contentType,body);const r=await sql<any>`INSERT INTO establishment_documents(id,organization_id,establishment_id,document_type,title,file_name,content_type,size_bytes,storage_key,issued_on,expires_on,notes,uploaded_by_user_id) VALUES(${id},${o},${e},${input.documentType},${input.title},${input.fileName},${input.contentType},${body.byteLength},${key},${input.issuedOn??null},${input.expiresOn??null},${input.notes??null},${u}) RETURNING id,document_type,title,file_name,content_type,size_bytes,issued_on,expires_on,notes,created_at`.execute(trx);return r.rows[0];});}
export async function getEstablishmentDocumentDownload(u:string,o:string,e:string,d:string){return withTenantContext({userId:u,organizationId:o},async trx=>{await allowed(trx,o,e);const r=await sql<any>`SELECT storage_key,file_name,content_type FROM establishment_documents WHERE id=${d} AND organization_id=${o} AND establishment_id=${e} AND archived_at IS NULL LIMIT 1`.execute(trx);if(!r.rows[0])throw new EstablishmentDocumentNotFoundError();return createPrivateDownloadUrl(r.rows[0].storage_key,r.rows[0].file_name,r.rows[0].content_type);});}
export async function archiveEstablishmentDocument(u:string,o:string,e:string,d:string){return withTenantContext({userId:u,organizationId:o},async trx=>{await allowed(trx,o,e);const r=await sql<any>`UPDATE establishment_documents SET archived_at=now(),updated_at=now() WHERE id=${d} AND organization_id=${o} AND establishment_id=${e} AND archived_at IS NULL RETURNING id`.execute(trx);if(!r.rows[0])throw new EstablishmentDocumentNotFoundError();});}
