import { randomUUID } from "node:crypto";
import { sql } from "kysely";
import { withTenantContext } from "../../context/tenantContext.js";
import { createPrivateDownloadUrl, uploadPrivateObject } from "../storage/objectStorage.js";
export class EstablishmentDocumentForbiddenError extends Error{constructor(){super("ESTABLISHMENT_DOCUMENT_FORBIDDEN");}}
export class EstablishmentDocumentNotFoundError extends Error{constructor(){super("ESTABLISHMENT_DOCUMENT_NOT_FOUND");}}
async function allowed(trx:any,o:string,e:string){const r=await sql<{allowed:boolean}>`SELECT EXISTS(SELECT 1 FROM locations l WHERE l.id=${e} AND l.organization_id=${o} AND (app_is_org_manager() OR app_is_superadmin() OR app_is_establishment_admin(${e}))) allowed`.execute(trx);if(!r.rows[0]?.allowed)throw new EstablishmentDocumentForbiddenError();}
async function platformReviewerOnly(trx:any,o:string,e:string){const r=await sql<{allowed:boolean}>`SELECT EXISTS(SELECT 1 FROM locations l WHERE l.id=${e} AND l.organization_id=${o} AND app_is_superadmin()) allowed`.execute(trx);if(!r.rows[0]?.allowed)throw new EstablishmentDocumentForbiddenError();}
const fields=sql.raw("id,document_type,title,file_name,content_type,size_bytes,issued_on,expires_on,notes,review_status,reviewed_by_user_id,reviewed_at,review_reason,created_at");
export async function listEstablishmentDocuments(u:string,o:string,e:string){return withTenantContext({userId:u,organizationId:o},async trx=>{await allowed(trx,o,e);const r=await sql<any>`SELECT ${fields} FROM establishment_documents WHERE organization_id=${o} AND establishment_id=${e} AND archived_at IS NULL ORDER BY created_at DESC`.execute(trx);return r.rows;});}
export async function uploadEstablishmentDocument(u:string,o:string,e:string,input:{documentType:string;title:string;fileName:string;contentType:string;issuedOn?:string;expiresOn?:string;notes?:string},body:Buffer){return withTenantContext({userId:u,organizationId:o},async trx=>{await allowed(trx,o,e);const id=randomUUID();const key=`establishment-documents/${o}/${e}/${id}/${input.fileName.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await uploadPrivateObject(key,input.contentType,body);await sql`UPDATE establishment_documents SET archived_at=now(),updated_at=now() WHERE organization_id=${o} AND establishment_id=${e} AND document_type=${input.documentType} AND archived_at IS NULL`.execute(trx);const r=await sql<any>`INSERT INTO establishment_documents(id,organization_id,establishment_id,document_type,title,file_name,content_type,size_bytes,storage_key,issued_on,expires_on,notes,uploaded_by_user_id,review_status) VALUES(${id},${o},${e},${input.documentType},${input.title},${input.fileName},${input.contentType},${body.byteLength},${key},${input.issuedOn??null},${input.expiresOn??null},${input.notes??null},${u},'pending') RETURNING ${fields}`.execute(trx);return r.rows[0];});}
export async function reviewEstablishmentDocument(u:string,o:string,e:string,d:string,status:'approved'|'rejected',reason?:string){return withTenantContext({userId:u,organizationId:o},async trx=>{await platformReviewerOnly(trx,o,e);const r=await sql<any>`UPDATE establishment_documents SET review_status=${status},reviewed_by_user_id=${u},reviewed_at=now(),review_reason=${reason??null},updated_at=now() WHERE id=${d} AND organization_id=${o} AND establishment_id=${e} AND archived_at IS NULL RETURNING ${fields}`.execute(trx);if(!r.rows[0])throw new EstablishmentDocumentNotFoundError();return r.rows[0];});}
export async function getEstablishmentDocumentDownload(u:string,o:string,e:string,d:string){return withTenantContext({userId:u,organizationId:o},async trx=>{await allowed(trx,o,e);const r=await sql<any>`SELECT storage_key,file_name,content_type FROM establishment_documents WHERE id=${d} AND organization_id=${o} AND establishment_id=${e} LIMIT 1`.execute(trx);if(!r.rows[0])throw new EstablishmentDocumentNotFoundError();return createPrivateDownloadUrl(r.rows[0].storage_key,r.rows[0].file_name,r.rows[0].content_type);});}
export async function archiveEstablishmentDocument(u:string,o:string,e:string,d:string){return withTenantContext({userId:u,organizationId:o},async trx=>{await allowed(trx,o,e);const r=await sql<any>`UPDATE establishment_documents SET archived_at=now(),updated_at=now() WHERE id=${d} AND organization_id=${o} AND establishment_id=${e} AND archived_at IS NULL RETURNING id`.execute(trx);if(!r.rows[0])throw new EstablishmentDocumentNotFoundError();});}
