import { Router,type Response } from "express";
import { z } from "zod";
import { requireAuth,type AuthenticatedRequest } from "../../middleware/auth.js";
import { archiveEstablishmentDocument,EstablishmentDocumentForbiddenError,EstablishmentDocumentNotFoundError,getEstablishmentDocumentDownload,listEstablishmentDocumentHistory,listEstablishmentDocuments,reviewEstablishmentDocument,uploadEstablishmentDocument } from "./establishmentDocuments.service.js";
const router=Router(),uuid=z.string().uuid();
function ids(req:AuthenticatedRequest){const o=uuid.safeParse(req.params.organizationId),e=uuid.safeParse(req.params.establishmentId);return o.success&&e.success?{o:o.data,e:e.data}:null;}
function fail(x:unknown,res:Response){if(x instanceof EstablishmentDocumentForbiddenError){res.status(403).json({error:"ESTABLISHMENT_DOCUMENT_FORBIDDEN"});return;}if(x instanceof EstablishmentDocumentNotFoundError){res.status(404).json({error:"ESTABLISHMENT_DOCUMENT_NOT_FOUND"});return;}res.status(500).json({error:"INTERNAL_ERROR"});}
router.get("/organizations/:organizationId/establishments/:establishmentId/documents",requireAuth,async(req:AuthenticatedRequest,res)=>{const p=ids(req);if(!p){res.status(400).json({error:"INVALID_ID"});return;}try{res.json({documents:await listEstablishmentDocuments(req.auth!.userId,p.o,p.e)});}catch(x){fail(x,res);}});
router.get("/organizations/:organizationId/establishments/:establishmentId/documents-history",requireAuth,async(req:AuthenticatedRequest,res)=>{const p=ids(req);if(!p){res.status(400).json({error:"INVALID_ID"});return;}const documentType=typeof req.query.documentType==='string'&&req.query.documentType.trim()?req.query.documentType.trim():undefined;try{res.json({documents:await listEstablishmentDocumentHistory(req.auth!.userId,p.o,p.e,documentType)});}catch(x){fail(x,res);}});
router.post("/organizations/:organizationId/establishments/:establishmentId/documents",requireAuth,async(req:AuthenticatedRequest,res)=>{const p=ids(req);if(!p){res.status(400).json({error:"INVALID_ID"});return;}const m=req.query,title=String(m.title??"").trim(),documentType=String(m.documentType??"").trim(),fileName=String(m.fileName??"").trim(),contentType=String(req.headers["content-type"]??"");if(!title||!documentType||!fileName||!contentType){res.status(400).json({error:"INVALID_PAYLOAD"});return;}const chunks:Buffer[]=[];let size=0;req.on("data",c=>{size+=c.length;if(size<=10*1024*1024)chunks.push(c);});req.on("end",async()=>{if(size>10*1024*1024){res.status(413).json({error:"FILE_TOO_LARGE"});return;}try{const document=await uploadEstablishmentDocument(req.auth!.userId,p.o,p.e,{title,documentType,fileName,contentType,issuedOn:m.issuedOn?String(m.issuedOn):undefined,expiresOn:m.expiresOn?String(m.expiresOn):undefined,notes:m.notes?String(m.notes):undefined},Buffer.concat(chunks));res.status(201).json({document});}catch(x){fail(x,res);}});});
router.patch("/organizations/:organizationId/establishments/:establishmentId/documents/:documentId/review",requireAuth,async(req:AuthenticatedRequest,res)=>{const p=ids(req),d=uuid.safeParse(req.params.documentId),body=z.object({status:z.enum(["approved","rejected"]),reason:z.string().trim().max(1000).optional()}).safeParse(req.body);if(!p||!d.success||!body.success){res.status(400).json({error:"INVALID_PAYLOAD"});return;}if(body.data.status==='rejected'&&!body.data.reason){res.status(400).json({error:"REJECTION_REASON_REQUIRED"});return;}try{res.json({document:await reviewEstablishmentDocument(req.auth!.userId,p.o,p.e,d.data,body.data.status,body.data.reason)});}catch(x){fail(x,res);}});
router.get("/organizations/:organizationId/establishments/:establishmentId/documents/:documentId/download",requireAuth,async(req:AuthenticatedRequest,res)=>{const p=ids(req),d=uuid.safeParse(req.params.documentId);if(!p||!d.success){res.status(400).json({error:"INVALID_ID"});return;}try{res.json({url:await getEstablishmentDocumentDownload(req.auth!.userId,p.o,p.e,d.data)});}catch(x){fail(x,res);}});
router.delete("/organizations/:organizationId/establishments/:establishmentId/documents/:documentId",requireAuth,async(req:AuthenticatedRequest,res)=>{const p=ids(req),d=uuid.safeParse(req.params.documentId);if(!p||!d.success){res.status(400).json({error:"INVALID_ID"});return;}try{await archiveEstablishmentDocument(req.auth!.userId,p.o,p.e,d.data);res.status(204).end();}catch(x){fail(x,res);}});
export default router;
