import { randomUUID } from "node:crypto";
import { sql } from "kysely";
import { withTenantContext } from "../../context/tenantContext.js";
import { createPrivateDownloadUrl, uploadPrivateObject } from "../storage/objectStorage.js";

export class ResidentDocumentForbiddenError extends Error { constructor(){super("RESIDENT_DOCUMENT_FORBIDDEN");} }
export class ResidentDocumentNotFoundError extends Error { constructor(){super("RESIDENT_DOCUMENT_NOT_FOUND");} }
async function assertManager(trx:any, organizationId:string, establishmentId:string, recipientId:string){
 const r=await sql<{allowed:boolean}>`SELECT EXISTS(SELECT 1 FROM care_recipients cr WHERE cr.id=${recipientId} AND cr.organization_id=${organizationId} AND cr.location_id=${establishmentId} AND cr.archived_at IS NULL AND (app_is_org_manager() OR app_is_superadmin() OR app_is_establishment_admin(${establishmentId}))) AS allowed`.execute(trx);
 if(!r.rows[0]?.allowed) throw new ResidentDocumentForbiddenError();
}
export async function listResidentDocuments(userId:string,organizationId:string,establishmentId:string,recipientId:string){return withTenantContext({userId,organizationId},async trx=>{await assertManager(trx,organizationId,establishmentId,recipientId);const r=await sql<any>`SELECT id,document_type,title,file_name,content_type,size_bytes,issued_on,expires_on,notes,created_at FROM resident_documents WHERE organization_id=${organizationId} AND establishment_id=${establishmentId} AND care_recipient_id=${recipientId} AND archived_at IS NULL ORDER BY created_at DESC`.execute(trx);return r.rows;});}
export async function uploadResidentDocument(userId:string,organizationId:string,establishmentId:string,recipientId:string,input:{documentType:string;title:string;fileName:string;contentType:string;issuedOn?:string;expiresOn?:string;notes?:string},body:Buffer){return withTenantContext({userId,organizationId},async trx=>{await assertManager(trx,organizationId,establishmentId,recipientId);const id=randomUUID();const storageKey=`resident-documents/${organizationId}/${establishmentId}/${recipientId}/${id}/${input.fileName.replace(/[^a-zA-Z0-9._-]/g,"_")}`;await uploadPrivateObject(storageKey,input.contentType,body);const r=await sql<any>`INSERT INTO resident_documents(id,organization_id,establishment_id,care_recipient_id,document_type,title,file_name,content_type,size_bytes,storage_key,issued_on,expires_on,notes,uploaded_by_user_id) VALUES(${id},${organizationId},${establishmentId},${recipientId},${input.documentType},${input.title},${input.fileName},${input.contentType},${body.byteLength},${storageKey},${input.issuedOn??null},${input.expiresOn??null},${input.notes??null},${userId}) RETURNING id,document_type,title,file_name,content_type,size_bytes,issued_on,expires_on,notes,created_at`.execute(trx);return r.rows[0];});}
export async function getResidentDocumentDownload(userId:string,organizationId:string,establishmentId:string,recipientId:string,documentId:string){return withTenantContext({userId,organizationId},async trx=>{await assertManager(trx,organizationId,establishmentId,recipientId);const r=await sql<{storage_key:string}>`SELECT storage_key FROM resident_documents WHERE id=${documentId} AND organization_id=${organizationId} AND establishment_id=${establishmentId} AND care_recipient_id=${recipientId} AND archived_at IS NULL LIMIT 1`.execute(trx);if(!r.rows[0])throw new ResidentDocumentNotFoundError();return createPrivateDownloadUrl(r.rows[0].storage_key);});}
export async function archiveResidentDocument(userId:string,organizationId:string,establishmentId:string,recipientId:string,documentId:string){return withTenantContext({userId,organizationId},async trx=>{await assertManager(trx,organizationId,establishmentId,recipientId);const r=await sql<{id:string}>`UPDATE resident_documents SET archived_at=now(),updated_at=now() WHERE id=${documentId} AND organization_id=${organizationId} AND establishment_id=${establishmentId} AND care_recipient_id=${recipientId} AND archived_at IS NULL RETURNING id`.execute(trx);if(!r.rows[0])throw new ResidentDocumentNotFoundError();return {id:documentId};});}
