import { Router, type Response } from "express";
import { z } from "zod";
import { requireAuth, type AuthenticatedRequest } from "../../middleware/auth.js";
import { archiveResidentDocument,getResidentDocumentDownload,listResidentDocuments,ResidentDocumentForbiddenError,ResidentDocumentNotFoundError,uploadResidentDocument } from "./residentDocuments.service.js";
const router=Router();const uuid=z.string().uuid();
function ids(req:AuthenticatedRequest){const o=uuid.safeParse(req.params.organizationId),e=uuid.safeParse(req.params.establishmentId),r=uuid.safeParse(req.params.recipientId);return o.success&&e.success&&r.success?{o:o.data,e:e.data,r:r.data}:null;}
function fail(error:unknown,res:Response){if(error instanceof ResidentDocumentForbiddenError){res.status(403).json({error:"RESIDENT_DOCUMENT_FORBIDDEN"});return;}if(error instanceof ResidentDocumentNotFoundError){res.status(404).json({error:"RESIDENT_DOCUMENT_NOT_FOUND"});return;}res.status(500).json({error:"INTERNAL_ERROR"});}
router.get("/organizations/:organizationId/establishments/:establishmentId/residents/:recipientId/documents",requireAuth,async(req:AuthenticatedRequest,res:Response)=>{const p=ids(req);if(!p){res.status(400).json({error:"INVALID_ID"});return;}try{res.json({documents:await listResidentDocuments(req.auth!.userId,p.o,p.e,p.r)});}catch(x){fail(x,res);}});
router.post("/organizations/:organizationId/establishments/:establishmentId/residents/:recipientId/documents",requireAuth,async(req:AuthenticatedRequest,res:Response)=>{const p=ids(req);if(!p){res.status(400).json({error:"INVALID_ID"});return;}const meta=req.query;const title=String(meta.title??"").trim(),documentType=String(meta.documentType??"").trim(),fileName=String(meta.fileName??"").trim(),contentType=String(req.headers["content-type"]??"");if(!title||!documentType||!fileName||!contentType){res.status(400).json({error:"INVALID_PAYLOAD"});return;}const chunks:Buffer[]=[];let size=0;req.on("data",c=>{size+=c.length;if(size<=10*1024*1024)chunks.push(c);});req.on("end",async()=>{if(size>10*1024*1024){res.status(413).json({error:"FILE_TOO_LARGE"});return;}try{const document=await uploadResidentDocument(req.auth!.userId,p.o,p.e,p.r,{title,documentType,fileName,contentType,issuedOn:meta.issuedOn?String(meta.issuedOn):undefined,expiresOn:meta.expiresOn?String(meta.expiresOn):undefined,notes:meta.notes?String(meta.notes):undefined},Buffer.concat(chunks));res.status(201).json({document});}catch(x){fail(x,res);}});});
router.get("/organizations/:organizationId/establishments/:establishmentId/residents/:recipientId/documents/:documentId/download",requireAuth,async(req:AuthenticatedRequest,res:Response)=>{const p=ids(req),d=uuid.safeParse(req.params.documentId);if(!p||!d.success){res.status(400).json({error:"INVALID_ID"});return;}try{res.json({url:await getResidentDocumentDownload(req.auth!.userId,p.o,p.e,p.r,d.data)});}catch(x){fail(x,res);}});
router.delete("/organizations/:organizationId/establishments/:establishmentId/residents/:recipientId/documents/:documentId",requireAuth,async(req:AuthenticatedRequest,res:Response)=>{const p=ids(req),d=uuid.safeParse(req.params.documentId);if(!p||!d.success){res.status(400).json({error:"INVALID_ID"});return;}try{await archiveResidentDocument(req.auth!.userId,p.o,p.e,p.r,d.data);res.status(204).end();}catch(x){fail(x,res);}});
export default router;
