import { randomUUID } from "node:crypto";
import { sql } from "kysely";
import { z } from "zod";
import { withTenantContext } from "../../context/tenantContext.js";
import { EstablishmentManagementForbiddenError, EstablishmentNotFoundError } from "./establishments.service.js";

export const createEstablishmentResidentSchema=z.object({firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().min(1).max(100),preferredName:z.string().trim().max(100).optional()});
export const updateEstablishmentResidentSchema=z.object({firstName:z.string().trim().min(1).max(100).optional(),lastName:z.string().trim().min(1).max(100).optional(),preferredName:z.string().trim().max(100).nullable().optional(),dateOfBirth:z.string().date().nullable().optional(),allergies:z.array(z.string().trim().min(1).max(200)).max(50).optional(),preferences:z.record(z.string(),z.unknown()).optional(),routines:z.record(z.string(),z.unknown()).optional(),status:z.enum(["active","inactive","archived"]).optional()}).refine(v=>Object.keys(v).length>0);
export const createEstablishmentWorkerSchema=z.object({displayName:z.string().trim().min(1).max(120),internalRole:z.string().trim().min(1).max(80).default("Caregiver")});
export const updateEstablishmentWorkerSchema=z.object({displayName:z.string().trim().min(1).max(120).optional(),internalRole:z.string().trim().min(1).max(80).optional(),status:z.enum(["active","inactive"]).optional()}).refine(v=>Object.keys(v).length>0);

async function assertAccess(trx:any,organizationId:string,establishmentId:string){const r=await sql<{allowed:boolean}>`SELECT EXISTS(SELECT 1 FROM locations WHERE id=${establishmentId} AND organization_id=${organizationId} AND archived_at IS NULL) AND app_is_establishment_admin(${establishmentId}::uuid) AS allowed`.execute(trx);if(!r.rows[0]?.allowed)throw new EstablishmentManagementForbiddenError();}

export function createEstablishmentResident(userId:string,organizationId:string,establishmentId:string,input:z.infer<typeof createEstablishmentResidentSchema>){return withTenantContext({userId,organizationId},async trx=>{await assertAccess(trx,organizationId,establishmentId);const id=randomUUID();await sql`INSERT INTO care_recipients(id,organization_id,location_id,first_name,last_name,preferred_name) VALUES(${id},${organizationId},${establishmentId},${input.firstName},${input.lastName},${input.preferredName??null})`.execute(trx);return{id,first_name:input.firstName,last_name:input.lastName,preferred_name:input.preferredName??null,status:"active"};});}
export function getEstablishmentResident(userId:string,organizationId:string,establishmentId:string,recipientId:string){return withTenantContext({userId,organizationId},async trx=>{await assertAccess(trx,organizationId,establishmentId);const row=await sql<any>`SELECT id,organization_id,location_id,first_name,last_name,preferred_name,date_of_birth,allergies,preferences,routines,status,room_id,created_at,updated_at FROM care_recipients WHERE id=${recipientId} AND organization_id=${organizationId} AND location_id=${establishmentId}`.execute(trx);if(!row.rows[0])throw new EstablishmentNotFoundError();return row.rows[0];});}
export function updateEstablishmentResident(userId:string,organizationId:string,establishmentId:string,recipientId:string,input:z.infer<typeof updateEstablishmentResidentSchema>){return withTenantContext({userId,organizationId},async trx=>{await assertAccess(trx,organizationId,establishmentId);const current=await sql<any>`SELECT id,first_name,last_name,preferred_name,date_of_birth,allergies,preferences,routines,status,room_id FROM care_recipients WHERE id=${recipientId} AND organization_id=${organizationId} AND location_id=${establishmentId}`.execute(trx);if(!current.rows[0])throw new EstablishmentNotFoundError();const c=current.rows[0];const next={firstName:input.firstName??c.first_name,lastName:input.lastName??c.last_name,preferredName:input.preferredName===undefined?c.preferred_name:input.preferredName,dateOfBirth:input.dateOfBirth===undefined?c.date_of_birth:input.dateOfBirth,allergies:input.allergies??c.allergies??[],preferences:input.preferences??c.preferences??{},routines:input.routines??c.routines??{},status:input.status??c.status};await sql`UPDATE care_recipients SET first_name=${next.firstName},last_name=${next.lastName},preferred_name=${next.preferredName},date_of_birth=${next.dateOfBirth},allergies=${JSON.stringify(next.allergies)}::jsonb,preferences=${JSON.stringify(next.preferences)}::jsonb,routines=${JSON.stringify(next.routines)}::jsonb,status=${next.status},updated_at=now() WHERE id=${recipientId} AND organization_id=${organizationId} AND location_id=${establishmentId}`.execute(trx);return{id:recipientId,first_name:next.firstName,last_name:next.lastName,preferred_name:next.preferredName,date_of_birth:next.dateOfBirth,allergies:next.allergies,preferences:next.preferences,routines:next.routines,status:next.status,room_id:c.room_id};});}
export function createEstablishmentWorker(userId:string,organizationId:string,establishmentId:string,input:z.infer<typeof createEstablishmentWorkerSchema>){return withTenantContext({userId,organizationId},async trx=>{await assertAccess(trx,organizationId,establishmentId);const workerId=randomUUID(),membershipId=randomUUID();await sql`INSERT INTO workers(id,display_name) VALUES(${workerId},${input.displayName})`.execute(trx);await sql`INSERT INTO organization_worker_memberships(id,worker_id,organization_id,internal_role) VALUES(${membershipId},${workerId},${organizationId},${input.internalRole})`.execute(trx);await sql`INSERT INTO establishment_worker_assignments(organization_id,location_id,organization_worker_membership_id,created_by_user_id) VALUES(${organizationId},${establishmentId},${membershipId},${userId})`.execute(trx);return{membership_id:membershipId,worker_id:workerId,display_name:input.displayName,role:input.internalRole,status:"active"};});}
export function updateEstablishmentWorker(userId:string,organizationId:string,establishmentId:string,membershipId:string,input:z.infer<typeof updateEstablishmentWorkerSchema>){return withTenantContext({userId,organizationId},async trx=>{await assertAccess(trx,organizationId,establishmentId);const current=await sql<any>`SELECT owm.id,owm.worker_id,owm.internal_role,owm.status,w.display_name FROM establishment_worker_assignments ewa JOIN organization_worker_memberships owm ON owm.id=ewa.organization_worker_membership_id AND owm.organization_id=ewa.organization_id JOIN workers w ON w.id=owm.worker_id WHERE ewa.organization_id=${organizationId} AND ewa.location_id=${establishmentId} AND ewa.organization_worker_membership_id=${membershipId} AND ewa.archived_at IS NULL`.execute(trx);if(!current.rows[0])throw new EstablishmentNotFoundError();const c=current.rows[0];if(input.displayName)await sql`UPDATE workers SET display_name=${input.displayName},updated_at=now() WHERE id=${c.worker_id}`.execute(trx);await sql`UPDATE organization_worker_memberships SET internal_role=${input.internalRole??c.internal_role},status=${input.status??c.status},ended_at=${input.status==="inactive"?new Date():null},updated_at=now() WHERE id=${membershipId} AND organization_id=${organizationId}`.execute(trx);return{membership_id:membershipId,worker_id:c.worker_id,display_name:input.displayName??c.display_name,role:input.internalRole??c.internal_role,status:input.status??c.status};});}
