import { sql } from "kysely";
import { z } from "zod";
import { withTenantContext } from "../../context/tenantContext.js";
import { TimesheetForbiddenError } from "./timesheets.service.js";

export const payPeriodSchema=z.object({dateFrom:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),dateTo:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),cadence:z.enum(["weekly","biweekly","custom"]).default("biweekly")}).refine(v=>v.dateFrom<=v.dateTo);
async function manager(trx:unknown){const r=await sql<{ok:boolean}>`SELECT app_is_org_manager() ok`.execute(trx as never);if(!r.rows[0]?.ok)throw new TimesheetForbiddenError()}
export async function previewPayPeriod(userId:string,organizationId:string,input:z.infer<typeof payPeriodSchema>){return withTenantContext({userId,organizationId},async trx=>{await manager(trx);const r=await sql<any>`
SELECT t.id,t.status,t.approved_minutes,t.pay_amount_cents,t.bill_amount_cents,w.display_name worker_name,m.internal_role,
CASE WHEN c.id IS NULL THEN NULL ELSE trim(concat_ws(' ',c.first_name,c.last_name)) END recipient_name
FROM timesheets t JOIN organization_worker_memberships m ON m.id=t.organization_worker_membership_id JOIN workers w ON w.id=m.worker_id LEFT JOIN care_recipients c ON c.id=t.care_recipient_id
WHERE t.organization_id=${organizationId} AND t.check_in_at>=${input.dateFrom}::date AND t.check_in_at<${input.dateTo}::date+interval '1 day' ORDER BY w.display_name,t.check_in_at`.execute(trx);
const rows=r.rows, approved=rows.filter((x:any)=>x.status==="approved");
const byWorker=new Map<string,any>();for(const x of approved){const k=x.worker_name??"Cuidador";const a=byWorker.get(k)??{workerName:k,approvedMinutes:0,payAmountCents:0,billAmountCents:0,timesheets:0};a.approvedMinutes+=Number(x.approved_minutes||0);a.payAmountCents+=Number(x.pay_amount_cents||0);a.billAmountCents+=Number(x.bill_amount_cents||0);a.timesheets++;byWorker.set(k,a)}
return {dateFrom:input.dateFrom,dateTo:input.dateTo,cadence:input.cadence,workers:[...byWorker.values()],exceptions:{pending:rows.filter((x:any)=>x.status==="pending").length,disputed:rows.filter((x:any)=>x.status==="disputed").length},summary:{approvedMinutes:approved.reduce((s:number,x:any)=>s+Number(x.approved_minutes||0),0),payAmountCents:approved.reduce((s:number,x:any)=>s+Number(x.pay_amount_cents||0),0),billAmountCents:approved.reduce((s:number,x:any)=>s+Number(x.bill_amount_cents||0),0),approvedTimesheets:approved.length}}})}
export async function closePayPeriod(userId:string,organizationId:string,input:z.infer<typeof payPeriodSchema>){return withTenantContext({userId,organizationId},async trx=>{await manager(trx);const pending=await sql<{count:number}>`SELECT count(*)::int count FROM timesheets WHERE organization_id=${organizationId} AND check_in_at>=${input.dateFrom}::date AND check_in_at<${input.dateTo}::date+interval '1 day' AND status<>'approved'`.execute(trx);if(Number(pending.rows[0]?.count||0)>0)throw new RangeError("PAY_PERIOD_HAS_EXCEPTIONS");
const created=await sql<any>`INSERT INTO pay_periods(organization_id,date_from,date_to,cadence,status,closed_by_user_id,closed_at) VALUES(${organizationId},${input.dateFrom},${input.dateTo},${input.cadence},'closed',${userId},now()) ON CONFLICT(organization_id,date_from,date_to) DO NOTHING RETURNING *`.execute(trx);if(!created.rows[0])throw new RangeError("PAY_PERIOD_ALREADY_EXISTS");const id=created.rows[0].id;
await sql`INSERT INTO pay_period_timesheets(pay_period_id,timesheet_id,organization_id,approved_minutes,pay_amount_cents,bill_amount_cents) SELECT ${id},id,${organizationId},approved_minutes,pay_amount_cents,bill_amount_cents FROM timesheets WHERE organization_id=${organizationId} AND check_in_at>=${input.dateFrom}::date AND check_in_at<${input.dateTo}::date+interval '1 day' AND status='approved'`.execute(trx);
const totals=await sql<any>`SELECT coalesce(sum(approved_minutes),0)::int approved_minutes,coalesce(sum(pay_amount_cents),0)::int pay_amount_cents,coalesce(sum(bill_amount_cents),0)::int bill_amount_cents FROM pay_period_timesheets WHERE pay_period_id=${id}`.execute(trx);const t=totals.rows[0];await sql`UPDATE pay_periods SET approved_minutes=${t.approved_minutes},pay_amount_cents=${t.pay_amount_cents},bill_amount_cents=${t.bill_amount_cents} WHERE id=${id}`.execute(trx);
await sql`INSERT INTO audit_log(actor_user_id,organization_id,target_organization_id,action,entity_type,entity_id,new_value) VALUES(${userId},${organizationId},${organizationId},'PAY_PERIOD_CLOSED','pay_period',${id},${JSON.stringify({dateFrom:input.dateFrom,dateTo:input.dateTo,...t})}::jsonb)`.execute(trx);return {id,status:"closed",...t}})}
export async function listPayPeriods(userId:string,organizationId:string){return withTenantContext({userId,organizationId},async trx=>{await manager(trx);return (await sql<any>`SELECT * FROM pay_periods WHERE organization_id=${organizationId} ORDER BY date_to DESC`.execute(trx)).rows})}
