import express, { type Express, type Request, type Response, type NextFunction } from "express";
import { env } from "./config/env.js";
import authRoutes from "./modules/auth/auth.routes.js";
import organizationContextRoutes from "./modules/organizationContext/organizationContext.routes.js";
import careRecipientsRoutes from "./modules/careRecipients/careRecipients.routes.js";
import familyRoutes from "./modules/family/family.routes.js";
import workforceRoutes from "./modules/workforce/workforce.routes.js";
import credentialingRoutes from "./modules/credentialing/credentialing.routes.js";
import eligibilityRoutes from "./modules/eligibility/eligibility.routes.js";
import schedulingRoutes from "./modules/scheduling/scheduling.routes.js";
import assignmentsRoutes from "./modules/assignments/assignments.routes.js";
import verificationRoutes from "./modules/verification/verification.routes.js";
import careEventsRoutes from "./modules/careEvents/careEvents.routes.js";
import observationsRoutes from "./modules/observations/observations.routes.js";
import incidentsRoutes from "./modules/incidents/incidents.routes.js";
import familyTimelineRoutes from "./modules/familyTimeline/familyTimeline.routes.js";
import messagingRoutes from "./modules/messaging/messaging.routes.js";
import notificationsRoutes from "./modules/notifications/notifications.routes.js";
import accessInvitationsRoutes from "./modules/accessInvitations/accessInvitations.routes.js";
import carePlansRoutes from "./modules/carePlans/carePlans.routes.js";
import coverageRoutes from "./modules/coverage/coverage.routes.js";
import availabilityRoutes from "./modules/availability/availability.routes.js";
import coverageOffersRoutes from "./modules/coverageOffers/coverageOffers.routes.js";
import workforcePlanningRoutes from "./modules/workforcePlanning/workforcePlanning.routes.js";
import timesheetsRoutes from "./modules/timesheets/timesheets.routes.js";
import payPeriodsRoutes from "./modules/timesheets/payPeriods.routes.js";
import operationsRoutes from "./modules/operations/operations.routes.js";
import coverageAgentRoutes from "./modules/coverageAgent/coverageAgent.routes.js";
import careQualityAgentRoutes from "./modules/careQualityAgent/careQualityAgent.routes.js";
import establishmentsRoutes from "./modules/establishments/establishments.routes.js";
import residentDocumentsRoutes from "./modules/residentDocuments/residentDocuments.routes.js";
import establishmentDocumentsRoutes from "./modules/establishmentDocuments/establishmentDocuments.routes.js";
import platformEstablishmentDocumentsRoutes from "./modules/establishmentDocuments/platformEstablishmentDocuments.routes.js";
import platformOrganizationsRoutes from "./modules/platformOrganizations/platformOrganizations.routes.js";
export function createApp():Express{const app=express();app.use(express.json());const allowedOrigins=new Set(["https://etnara-care.github.io",...env.ALLOWED_ORIGIN.split(",").map(o=>o.trim()).filter(Boolean)]);app.use((req:Request,res:Response,next:NextFunction)=>{const origin=req.headers.origin;if(origin&&allowedOrigins.has(origin)){res.setHeader("Access-Control-Allow-Origin",origin);res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Methods","GET,POST,PUT,PATCH,DELETE,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization");}if(req.method==="OPTIONS"){res.status(204).end();return;}next();});app.get("/health",(_req,res)=>{res.status(200).json({status:"ok"});});app.use(authRoutes);app.use(organizationContextRoutes);app.use(platformOrganizationsRoutes);app.use(platformEstablishmentDocumentsRoutes);app.use(careRecipientsRoutes);app.use(familyRoutes);app.use(workforceRoutes);app.use(credentialingRoutes);app.use(eligibilityRoutes);app.use(schedulingRoutes);app.use(assignmentsRoutes);app.use(verificationRoutes);app.use(careEventsRoutes);app.use(observationsRoutes);app.use(incidentsRoutes);app.use(familyTimelineRoutes);app.use(messagingRoutes);app.use(notificationsRoutes);app.use(accessInvitationsRoutes);app.use(carePlansRoutes);app.use(coverageRoutes);app.use(availabilityRoutes);app.use(coverageOffersRoutes);app.use(workforcePlanningRoutes);app.use(timesheetsRoutes);app.use(payPeriodsRoutes);app.use(operationsRoutes);app.use(coverageAgentRoutes);app.use(careQualityAgentRoutes);app.use(establishmentsRoutes);app.use(residentDocumentsRoutes);app.use(establishmentDocumentsRoutes);app.use((err:unknown,_req:Request,res:Response,_next:NextFunction)=>{res.status(500).json({error:"INTERNAL_ERROR"});});return app;}
